services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: envoy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - envoy-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - envoy-network

#   envoy:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: envoy
#     environment:
#       DATABASE_URL: postgres://user:password@postgres:5432/envoy
#       REDIS_URL: redis://redis:6379
#     depends_on:
#       - postgres
#       - redis
#     ports:
#       - "8001:8001"
#     networks:
#       - envoy-network

volumes:
  postgres_data:

networks:
  envoy-network:
    driver: bridge
