definitions:
  src_controller.UserDTO:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      nickname:
        type: string
      passworddigest:
        type: string
      uid:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://example.com/support
  description: This is a sample API
  termsOfService: http://example.com/terms/
  title: Envoy Builder API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Returns the server health status as a simple "OK" message.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get the health status of the server
      tags:
      - health
  /users:
    get:
      consumes:
      - application/json
      description: Fetch all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/src_controller.UserDTO'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User details
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/src_controller.UserDTO'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            $ref: '#/definitions/src_controller.UserDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new user
      tags:
      - Users
  /users/{userId}:
    get:
      consumes:
      - application/json
      description: Fetches user details using the provided user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User details
          schema:
            $ref: '#/definitions/src_controller.UserDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a user by ID
      tags:
      - Users
swagger: "2.0"
