basePath: /api/v1
definitions:
  github_com_danielmoisa_envoy_src_model.Candidate:
    properties:
      createdAt:
        type: string
      experience:
        description: Years of experience
        type: integer
      id:
        type: string
      is_available:
        type: boolean
      skills:
        items:
          $ref: '#/definitions/github_com_danielmoisa_envoy_src_model.Skill'
        type: array
      summary:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      user_id:
        type: string
    type: object
  github_com_danielmoisa_envoy_src_model.Company:
    properties:
      company_logo:
        type: string
      company_name:
        type: string
      company_size:
        type: string
      company_website:
        type: string
      createdAt:
        type: string
      id:
        type: string
      industry:
        type: string
      updatedAt:
        type: string
      user_id:
        type: string
    type: object
  github_com_danielmoisa_envoy_src_model.Skill:
    properties:
      category:
        type: string
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  github_com_danielmoisa_envoy_src_model.User:
    properties:
      avatar:
        type: string
      candidate:
        allOf:
        - $ref: '#/definitions/github_com_danielmoisa_envoy_src_model.Candidate'
        description: Associations
      company:
        $ref: '#/definitions/github_com_danielmoisa_envoy_src_model.Company'
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      role:
        $ref: '#/definitions/github_com_danielmoisa_envoy_src_model.UserRole'
      update_at:
        type: string
      username:
        type: string
    type: object
  github_com_danielmoisa_envoy_src_model.UserRole:
    enum:
    - candidate
    - company
    - admin
    type: string
    x-enum-varnames:
    - RoleCandidate
    - RoleCompany
    - RoleAdmin
  github_com_danielmoisa_envoy_src_request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github_com_danielmoisa_envoy_src_response.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/github_com_danielmoisa_envoy_src_model.User'
    type: object
  src_controller.UserDTO:
    properties:
      avatar:
        type: string
      candidate:
        allOf:
        - $ref: '#/definitions/github_com_danielmoisa_envoy_src_model.Candidate'
        description: Associations
      company:
        $ref: '#/definitions/github_com_danielmoisa_envoy_src_model.Company'
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      role:
        $ref: '#/definitions/github_com_danielmoisa_envoy_src_model.UserRole'
      update_at:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://example.com/support
  description: This is a sample API
  termsOfService: http://example.com/terms/
  title: Envoy API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: Login Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/github_com_danielmoisa_envoy_src_request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_danielmoisa_envoy_src_response.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User login
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout user (client-side token removal)
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged out
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User logout
      tags:
      - Auth
  /health:
    get:
      consumes:
      - application/json
      description: Returns the server health status as a simple "OK" message.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get the health status of the server
      tags:
      - health
  /users:
    get:
      consumes:
      - application/json
      description: Fetch all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/src_controller.UserDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User details
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/src_controller.UserDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/src_controller.UserDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Create a new user
      tags:
      - Users
  /users/{userId}:
    delete:
      consumes:
      - application/json
      description: Delete a user by their unique user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Delete a user by ID
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Fetches user details using the provided user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/src_controller.UserDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Get a user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update a user by their unique user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      - description: User details
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/src_controller.UserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/src_controller.UserDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Update a user by ID
      tags:
      - Users
securityDefinitions:
  Bearer:
    description: 'Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
